# Generated by Django 2.2 on 2021-02-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210226_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
